version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
      maven: 3.9
    commands:
      - echo Using preinstalled Java 11 and Maven 3.9...
      - mvn -v
  build:
    commands:
      - echo Building the Java application...
      - mvn clean package

artifacts:
  files:
    - target/*.jar