version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven manually...
      - curl -L -O https://archive.apache.org/dist/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - file apache-maven-3.9.6-bin.tar.gz
      - tar -xvzf apache-maven-3.9.6-bin.tar.gz
      - mv apache-maven-3.9.6 /opt/maven
      - export M2_HOME=/opt/maven
      - export PATH=$M2_HOME/bin:$PATH
      - "echo Maven version:"
      - /opt/maven/bin/mvn -v
  build:
    commands:
      - echo Building the Java application...
      - /opt/maven/bin/mvn clean package

artifacts:
  files:
    - target/*.jar