version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Java and Maven manually...
      - yum install -y java-1.8.0-openjdk
      - curl -O https://downloads.apache.org/maven/maven-3/3.9.6/binaries/apache-maven-3.9.6-bin.tar.gz
      - tar -xvzf apache-maven-3.9.6-bin.tar.gz
      - mv apache-maven-3.9.6 /opt/maven
      - export M2_HOME=/opt/maven
      - export PATH=$M2_HOME/bin:$PATH
      - echo Maven version:latest
      - /opt/maven/bin/mvn -v
  build:
    commands:
      - echo Building the Java application...
      - /opt/maven/bin/mvn clean package

artifacts:
  files:
    - target/*.jar