version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - sudo yum update && sudo yum install -y maven
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/*.jar
